/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Review {
    date: bigint;
    user: string;
    comment: string;
    rating: bigint;
    verificationStatus: ReviewStatus;
}
export interface TravelPackageType {
    id: bigint;
    durationDays: bigint;
    startValidity: bigint;
    reviews: Array<Review>;
    name: string;
    description: string;
    endLocation: string;
    availableSpots: bigint;
    category: ThemeType;
    rating: bigint;
    endValidity: bigint;
    price: bigint;
    discountPercentage?: bigint;
    includedServices: Array<IncludedService>;
    startLocation: string;
    itinerary: Array<Itinerary>;
    images: Array<ExternalBlob>;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Destination {
    id: bigint;
    theme: ThemeType;
    itineraries: Array<Itinerary>;
    name: string;
    description: string;
    travelPackages: Array<TravelPackageType>;
    isFeatured: boolean;
    price: bigint;
    location: string;
    images: Array<ExternalBlob>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Itinerary {
    day: bigint;
    title: string;
    description: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface IncludedService {
    availabilityStart?: bigint;
    cost: bigint;
    name: string;
    type: IncludedServiceType;
    description: string;
    availabilityEnd?: bigint;
    rating: bigint;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Booking {
    id: bigint;
    paymentStatus: PaymentStatus;
    user: Principal;
    bookingStatus: BookingStatus;
    stripeSessionId?: string;
    packageId: bigint;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
    email: string;
    phone: string;
}
export enum BookingStatus {
    canceled = "canceled",
    pending = "pending",
    confirmed = "confirmed"
}
export enum IncludedServiceType {
    meals = "meals",
    transportation = "transportation",
    tours = "tours",
    accommodation = "accommodation",
    insurance = "insurance",
    guide = "guide"
}
export enum PaymentStatus {
    pending = "pending",
    paid = "paid",
    failed = "failed"
}
export enum ReviewStatus {
    submitted = "submitted",
    approved = "approved",
    rejected = "rejected"
}
export enum ThemeType {
    nature = "nature",
    romantic = "romantic",
    cultural = "cultural",
    adventure = "adventure",
    luxury = "luxury",
    family = "family"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDestination(newDestination: Destination): Promise<bigint>;
    addTravelPackage(newPackage: TravelPackageType): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelBooking(id: bigint): Promise<void>;
    createBooking(packageId: bigint): Promise<bigint>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    deleteDestination(id: bigint): Promise<void>;
    deleteTravelPackage(id: bigint): Promise<void>;
    filterByCategory(category: ThemeType): Promise<Array<TravelPackageType>>;
    filterByLocation(location: string): Promise<Array<TravelPackageType>>;
    filterByPriceRange(minPrice: bigint, maxPrice: bigint): Promise<Array<TravelPackageType>>;
    filterReviewsByRating(minRating: bigint, maxRating: bigint): Promise<Array<Review>>;
    filterServices(serviceType: IncludedServiceType, minRating: bigint, priceRange: {
        max: bigint;
        min: bigint;
    }, availability: {
        end?: bigint;
        start?: bigint;
    }): Promise<Array<IncludedService>>;
    filterServicesByAvailability(start: bigint | null, end: bigint | null): Promise<Array<IncludedService>>;
    getAllBookings(): Promise<Array<Booking>>;
    getAllByPriceAscending(): Promise<Array<TravelPackageType>>;
    getAllDestinations(): Promise<Array<Destination>>;
    getAllServices(): Promise<Array<IncludedService>>;
    getAllTravelPackages(): Promise<Array<TravelPackageType>>;
    getAvailableServices(): Promise<Array<IncludedService>>;
    getAvailableSpotsFilter(): Promise<Array<TravelPackageType>>;
    getBooking(id: bigint): Promise<Booking | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomQuestionnaire(countryName: string): Promise<string>;
    getDestination(id: bigint): Promise<Destination | null>;
    getMyBookings(): Promise<Array<Booking>>;
    getPackageCategoryFilter(category: ThemeType): Promise<Array<TravelPackageType>>;
    getReviewsForPackage(packageId: bigint): Promise<Array<Review>>;
    getServicesByType(serviceType: IncludedServiceType): Promise<Array<IncludedService>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getTravelPackage(id: bigint): Promise<TravelPackageType | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVerifiedReviews(): Promise<Array<Review>>;
    getWithAvailableSpots(): Promise<Array<TravelPackageType>>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchByName(searchText: string): Promise<Array<TravelPackageType>>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateBookingStatus(id: bigint, status: BookingStatus): Promise<void>;
    updateDestination(id: bigint, updatedDestination: Destination): Promise<void>;
    updatePaymentStatus(id: bigint, status: PaymentStatus): Promise<void>;
    updateTravelPackage(id: bigint, updatedPackage: TravelPackageType): Promise<void>;
}
import type { Booking as _Booking, BookingStatus as _BookingStatus, Destination as _Destination, ExternalBlob as _ExternalBlob, IncludedService as _IncludedService, IncludedServiceType as _IncludedServiceType, Itinerary as _Itinerary, PaymentStatus as _PaymentStatus, Review as _Review, ReviewStatus as _ReviewStatus, StripeSessionStatus as _StripeSessionStatus, ThemeType as _ThemeType, TravelPackageType as _TravelPackageType, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDestination(arg0: Destination): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addDestination(await to_candid_Destination_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDestination(await to_candid_Destination_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addTravelPackage(arg0: TravelPackageType): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTravelPackage(await to_candid_TravelPackageType_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTravelPackage(await to_candid_TravelPackageType_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n27(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n27(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelBooking(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0);
            return result;
        }
    }
    async createBooking(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteDestination(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDestination(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDestination(arg0);
            return result;
        }
    }
    async deleteTravelPackage(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTravelPackage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTravelPackage(arg0);
            return result;
        }
    }
    async filterByCategory(arg0: ThemeType): Promise<Array<TravelPackageType>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterByCategory(to_candid_ThemeType_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterByCategory(to_candid_ThemeType_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterByLocation(arg0: string): Promise<Array<TravelPackageType>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterByLocation(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterByLocation(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterByPriceRange(arg0: bigint, arg1: bigint): Promise<Array<TravelPackageType>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterByPriceRange(arg0, arg1);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterByPriceRange(arg0, arg1);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterReviewsByRating(arg0: bigint, arg1: bigint): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterReviewsByRating(arg0, arg1);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterReviewsByRating(arg0, arg1);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterServices(arg0: IncludedServiceType, arg1: bigint, arg2: {
        max: bigint;
        min: bigint;
    }, arg3: {
        end?: bigint;
        start?: bigint;
    }): Promise<Array<IncludedService>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterServices(to_candid_IncludedServiceType_n23(this._uploadFile, this._downloadFile, arg0), arg1, arg2, to_candid_record_n46(this._uploadFile, this._downloadFile, arg3));
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterServices(to_candid_IncludedServiceType_n23(this._uploadFile, this._downloadFile, arg0), arg1, arg2, to_candid_record_n46(this._uploadFile, this._downloadFile, arg3));
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterServicesByAvailability(arg0: bigint | null, arg1: bigint | null): Promise<Array<IncludedService>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterServicesByAvailability(to_candid_opt_n47(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n47(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterServicesByAvailability(to_candid_opt_n47(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n47(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllByPriceAscending(): Promise<Array<TravelPackageType>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllByPriceAscending();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllByPriceAscending();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDestinations(): Promise<Array<Destination>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDestinations();
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDestinations();
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllServices(): Promise<Array<IncludedService>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllServices();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllServices();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTravelPackages(): Promise<Array<TravelPackageType>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTravelPackages();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTravelPackages();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableServices(): Promise<Array<IncludedService>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableServices();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableServices();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableSpotsFilter(): Promise<Array<TravelPackageType>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableSpotsFilter();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableSpotsFilter();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBooking(arg0: bigint): Promise<Booking | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomQuestionnaire(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomQuestionnaire(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomQuestionnaire(arg0);
            return result;
        }
    }
    async getDestination(arg0: bigint): Promise<Destination | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDestination(arg0);
                return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDestination(arg0);
            return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBookings();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBookings();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPackageCategoryFilter(arg0: ThemeType): Promise<Array<TravelPackageType>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPackageCategoryFilter(to_candid_ThemeType_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPackageCategoryFilter(to_candid_ThemeType_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReviewsForPackage(arg0: bigint): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviewsForPackage(arg0);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviewsForPackage(arg0);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServicesByType(arg0: IncludedServiceType): Promise<Array<IncludedService>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServicesByType(to_candid_IncludedServiceType_n23(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServicesByType(to_candid_IncludedServiceType_n23(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTravelPackage(arg0: bigint): Promise<TravelPackageType | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTravelPackage(arg0);
                return from_candid_opt_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTravelPackage(arg0);
            return from_candid_opt_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVerifiedReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVerifiedReviews();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVerifiedReviews();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWithAvailableSpots(): Promise<Array<TravelPackageType>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWithAvailableSpots();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWithAvailableSpots();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchByName(arg0: string): Promise<Array<TravelPackageType>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchByName(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchByName(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateBookingStatus(arg0: bigint, arg1: BookingStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n68(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n68(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateDestination(arg0: bigint, arg1: Destination): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDestination(arg0, await to_candid_Destination_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDestination(arg0, await to_candid_Destination_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePaymentStatus(arg0: bigint, arg1: PaymentStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePaymentStatus(arg0, to_candid_PaymentStatus_n70(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePaymentStatus(arg0, to_candid_PaymentStatus_n70(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTravelPackage(arg0: bigint, arg1: TravelPackageType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTravelPackage(arg0, await to_candid_TravelPackageType_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTravelPackage(arg0, await to_candid_TravelPackageType_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_BookingStatus_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
async function from_candid_Destination_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Destination): Promise<Destination> {
    return await from_candid_record_n58(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_IncludedServiceType_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IncludedServiceType): IncludedServiceType {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_IncludedService_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IncludedService): IncludedService {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function from_candid_ReviewStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReviewStatus): ReviewStatus {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Review_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Review): Review {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n65(_uploadFile, _downloadFile, value);
}
function from_candid_ThemeType_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ThemeType): ThemeType {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
async function from_candid_TravelPackageType_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TravelPackageType): Promise<TravelPackageType> {
    return await from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n62(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Booking]): Booking | null {
    return value.length === 0 ? null : from_candid_Booking_n49(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Destination]): Promise<Destination | null> {
    return value.length === 0 ? null : await from_candid_Destination_n57(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TravelPackageType]): Promise<TravelPackageType | null> {
    return value.length === 0 ? null : await from_candid_TravelPackageType_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    durationDays: bigint;
    startValidity: bigint;
    reviews: Array<_Review>;
    name: string;
    description: string;
    endLocation: string;
    availableSpots: bigint;
    category: _ThemeType;
    rating: bigint;
    endValidity: bigint;
    price: bigint;
    discountPercentage: [] | [bigint];
    includedServices: Array<_IncludedService>;
    startLocation: string;
    itinerary: Array<_Itinerary>;
    images: Array<_ExternalBlob>;
}): Promise<{
    id: bigint;
    durationDays: bigint;
    startValidity: bigint;
    reviews: Array<Review>;
    name: string;
    description: string;
    endLocation: string;
    availableSpots: bigint;
    category: ThemeType;
    rating: bigint;
    endValidity: bigint;
    price: bigint;
    discountPercentage?: bigint;
    includedServices: Array<IncludedService>;
    startLocation: string;
    itinerary: Array<Itinerary>;
    images: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        durationDays: value.durationDays,
        startValidity: value.startValidity,
        reviews: from_candid_vec_n32(_uploadFile, _downloadFile, value.reviews),
        name: value.name,
        description: value.description,
        endLocation: value.endLocation,
        availableSpots: value.availableSpots,
        category: from_candid_ThemeType_n37(_uploadFile, _downloadFile, value.category),
        rating: value.rating,
        endValidity: value.endValidity,
        price: value.price,
        discountPercentage: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.discountPercentage)),
        includedServices: from_candid_vec_n39(_uploadFile, _downloadFile, value.includedServices),
        startLocation: value.startLocation,
        itinerary: value.itinerary,
        images: await from_candid_vec_n44(_uploadFile, _downloadFile, value.images)
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: bigint;
    user: string;
    comment: string;
    rating: bigint;
    verificationStatus: _ReviewStatus;
}): {
    date: bigint;
    user: string;
    comment: string;
    rating: bigint;
    verificationStatus: ReviewStatus;
} {
    return {
        date: value.date,
        user: value.user,
        comment: value.comment,
        rating: value.rating,
        verificationStatus: from_candid_ReviewStatus_n35(_uploadFile, _downloadFile, value.verificationStatus)
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    availabilityStart: [] | [bigint];
    cost: bigint;
    name: string;
    type: _IncludedServiceType;
    description: string;
    availabilityEnd: [] | [bigint];
    rating: bigint;
}): {
    availabilityStart?: bigint;
    cost: bigint;
    name: string;
    type: IncludedServiceType;
    description: string;
    availabilityEnd?: bigint;
    rating: bigint;
} {
    return {
        availabilityStart: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.availabilityStart)),
        cost: value.cost,
        name: value.name,
        type: from_candid_IncludedServiceType_n42(_uploadFile, _downloadFile, value.type),
        description: value.description,
        availabilityEnd: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.availabilityEnd)),
        rating: value.rating
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    paymentStatus: _PaymentStatus;
    user: Principal;
    bookingStatus: _BookingStatus;
    stripeSessionId: [] | [string];
    packageId: bigint;
}): {
    id: bigint;
    paymentStatus: PaymentStatus;
    user: Principal;
    bookingStatus: BookingStatus;
    stripeSessionId?: string;
    packageId: bigint;
} {
    return {
        id: value.id,
        paymentStatus: from_candid_PaymentStatus_n51(_uploadFile, _downloadFile, value.paymentStatus),
        user: value.user,
        bookingStatus: from_candid_BookingStatus_n53(_uploadFile, _downloadFile, value.bookingStatus),
        stripeSessionId: record_opt_to_undefined(from_candid_opt_n55(_uploadFile, _downloadFile, value.stripeSessionId)),
        packageId: value.packageId
    };
}
async function from_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    theme: _ThemeType;
    itineraries: Array<_Itinerary>;
    name: string;
    description: string;
    travelPackages: Array<_TravelPackageType>;
    isFeatured: boolean;
    price: bigint;
    location: string;
    images: Array<_ExternalBlob>;
}): Promise<{
    id: bigint;
    theme: ThemeType;
    itineraries: Array<Itinerary>;
    name: string;
    description: string;
    travelPackages: Array<TravelPackageType>;
    isFeatured: boolean;
    price: bigint;
    location: string;
    images: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        theme: from_candid_ThemeType_n37(_uploadFile, _downloadFile, value.theme),
        itineraries: value.itineraries,
        name: value.name,
        description: value.description,
        travelPackages: await from_candid_vec_n29(_uploadFile, _downloadFile, value.travelPackages),
        isFeatured: value.isFeatured,
        price: value.price,
        location: value.location,
        images: await from_candid_vec_n44(_uploadFile, _downloadFile, value.images)
    };
}
function from_candid_record_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n55(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    submitted: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ReviewStatus {
    return "submitted" in value ? ReviewStatus.submitted : "approved" in value ? ReviewStatus.approved : "rejected" in value ? ReviewStatus.rejected : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nature: null;
} | {
    romantic: null;
} | {
    cultural: null;
} | {
    adventure: null;
} | {
    luxury: null;
} | {
    family: null;
}): ThemeType {
    return "nature" in value ? ThemeType.nature : "romantic" in value ? ThemeType.romantic : "cultural" in value ? ThemeType.cultural : "adventure" in value ? ThemeType.adventure : "luxury" in value ? ThemeType.luxury : "family" in value ? ThemeType.family : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    meals: null;
} | {
    transportation: null;
} | {
    tours: null;
} | {
    accommodation: null;
} | {
    insurance: null;
} | {
    guide: null;
}): IncludedServiceType {
    return "meals" in value ? IncludedServiceType.meals : "transportation" in value ? IncludedServiceType.transportation : "tours" in value ? IncludedServiceType.tours : "accommodation" in value ? IncludedServiceType.accommodation : "insurance" in value ? IncludedServiceType.insurance : "guide" in value ? IncludedServiceType.guide : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
} | {
    failed: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "paid" in value ? PaymentStatus.paid : "failed" in value ? PaymentStatus.failed : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    canceled: null;
} | {
    pending: null;
} | {
    confirmed: null;
}): BookingStatus {
    return "canceled" in value ? BookingStatus.canceled : "pending" in value ? BookingStatus.pending : "confirmed" in value ? BookingStatus.confirmed : value;
}
function from_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n66(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
async function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TravelPackageType>): Promise<Array<TravelPackageType>> {
    return await Promise.all(value.map(async (x)=>await from_candid_TravelPackageType_n30(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Review>): Array<Review> {
    return value.map((x)=>from_candid_Review_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_IncludedService>): Array<IncludedService> {
    return value.map((x)=>from_candid_IncludedService_n40(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n45(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n49(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Destination>): Promise<Array<Destination>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Destination_n57(_uploadFile, _downloadFile, x)));
}
function to_candid_BookingStatus_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n69(_uploadFile, _downloadFile, value);
}
async function to_candid_Destination_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Destination): Promise<_Destination> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_IncludedServiceType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IncludedServiceType): _IncludedServiceType {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_IncludedService_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IncludedService): _IncludedService {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n71(_uploadFile, _downloadFile, value);
}
function to_candid_ReviewStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReviewStatus): _ReviewStatus {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_Review_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Review): _Review {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_ThemeType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ThemeType): _ThemeType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_TravelPackageType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TravelPackageType): Promise<_TravelPackageType> {
    return await to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    durationDays: bigint;
    startValidity: bigint;
    reviews: Array<Review>;
    name: string;
    description: string;
    endLocation: string;
    availableSpots: bigint;
    category: ThemeType;
    rating: bigint;
    endValidity: bigint;
    price: bigint;
    discountPercentage?: bigint;
    includedServices: Array<IncludedService>;
    startLocation: string;
    itinerary: Array<Itinerary>;
    images: Array<ExternalBlob>;
}): Promise<{
    id: bigint;
    durationDays: bigint;
    startValidity: bigint;
    reviews: Array<_Review>;
    name: string;
    description: string;
    endLocation: string;
    availableSpots: bigint;
    category: _ThemeType;
    rating: bigint;
    endValidity: bigint;
    price: bigint;
    discountPercentage: [] | [bigint];
    includedServices: Array<_IncludedService>;
    startLocation: string;
    itinerary: Array<_Itinerary>;
    images: Array<_ExternalBlob>;
}> {
    return {
        id: value.id,
        durationDays: value.durationDays,
        startValidity: value.startValidity,
        reviews: to_candid_vec_n15(_uploadFile, _downloadFile, value.reviews),
        name: value.name,
        description: value.description,
        endLocation: value.endLocation,
        availableSpots: value.availableSpots,
        category: to_candid_ThemeType_n10(_uploadFile, _downloadFile, value.category),
        rating: value.rating,
        endValidity: value.endValidity,
        price: value.price,
        discountPercentage: value.discountPercentage ? candid_some(value.discountPercentage) : candid_none(),
        includedServices: to_candid_vec_n20(_uploadFile, _downloadFile, value.includedServices),
        startLocation: value.startLocation,
        itinerary: value.itinerary,
        images: await to_candid_vec_n25(_uploadFile, _downloadFile, value.images)
    };
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: bigint;
    user: string;
    comment: string;
    rating: bigint;
    verificationStatus: ReviewStatus;
}): {
    date: bigint;
    user: string;
    comment: string;
    rating: bigint;
    verificationStatus: _ReviewStatus;
} {
    return {
        date: value.date,
        user: value.user,
        comment: value.comment,
        rating: value.rating,
        verificationStatus: to_candid_ReviewStatus_n18(_uploadFile, _downloadFile, value.verificationStatus)
    };
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    availabilityStart?: bigint;
    cost: bigint;
    name: string;
    type: IncludedServiceType;
    description: string;
    availabilityEnd?: bigint;
    rating: bigint;
}): {
    availabilityStart: [] | [bigint];
    cost: bigint;
    name: string;
    type: _IncludedServiceType;
    description: string;
    availabilityEnd: [] | [bigint];
    rating: bigint;
} {
    return {
        availabilityStart: value.availabilityStart ? candid_some(value.availabilityStart) : candid_none(),
        cost: value.cost,
        name: value.name,
        type: to_candid_IncludedServiceType_n23(_uploadFile, _downloadFile, value.type),
        description: value.description,
        availabilityEnd: value.availabilityEnd ? candid_some(value.availabilityEnd) : candid_none(),
        rating: value.rating
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    end?: bigint;
    start?: bigint;
}): {
    end: [] | [bigint];
    start: [] | [bigint];
} {
    return {
        end: value.end ? candid_some(value.end) : candid_none(),
        start: value.start ? candid_some(value.start) : candid_none()
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    theme: ThemeType;
    itineraries: Array<Itinerary>;
    name: string;
    description: string;
    travelPackages: Array<TravelPackageType>;
    isFeatured: boolean;
    price: bigint;
    location: string;
    images: Array<ExternalBlob>;
}): Promise<{
    id: bigint;
    theme: _ThemeType;
    itineraries: Array<_Itinerary>;
    name: string;
    description: string;
    travelPackages: Array<_TravelPackageType>;
    isFeatured: boolean;
    price: bigint;
    location: string;
    images: Array<_ExternalBlob>;
}> {
    return {
        id: value.id,
        theme: to_candid_ThemeType_n10(_uploadFile, _downloadFile, value.theme),
        itineraries: value.itineraries,
        name: value.name,
        description: value.description,
        travelPackages: await to_candid_vec_n12(_uploadFile, _downloadFile, value.travelPackages),
        isFeatured: value.isFeatured,
        price: value.price,
        location: value.location,
        images: await to_candid_vec_n25(_uploadFile, _downloadFile, value.images)
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ThemeType): {
    nature: null;
} | {
    romantic: null;
} | {
    cultural: null;
} | {
    adventure: null;
} | {
    luxury: null;
} | {
    family: null;
} {
    return value == ThemeType.nature ? {
        nature: null
    } : value == ThemeType.romantic ? {
        romantic: null
    } : value == ThemeType.cultural ? {
        cultural: null
    } : value == ThemeType.adventure ? {
        adventure: null
    } : value == ThemeType.luxury ? {
        luxury: null
    } : value == ThemeType.family ? {
        family: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReviewStatus): {
    submitted: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ReviewStatus.submitted ? {
        submitted: null
    } : value == ReviewStatus.approved ? {
        approved: null
    } : value == ReviewStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IncludedServiceType): {
    meals: null;
} | {
    transportation: null;
} | {
    tours: null;
} | {
    accommodation: null;
} | {
    insurance: null;
} | {
    guide: null;
} {
    return value == IncludedServiceType.meals ? {
        meals: null
    } : value == IncludedServiceType.transportation ? {
        transportation: null
    } : value == IncludedServiceType.tours ? {
        tours: null
    } : value == IncludedServiceType.accommodation ? {
        accommodation: null
    } : value == IncludedServiceType.insurance ? {
        insurance: null
    } : value == IncludedServiceType.guide ? {
        guide: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    canceled: null;
} | {
    pending: null;
} | {
    confirmed: null;
} {
    return value == BookingStatus.canceled ? {
        canceled: null
    } : value == BookingStatus.pending ? {
        pending: null
    } : value == BookingStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    pending: null;
} | {
    paid: null;
} | {
    failed: null;
} {
    return value == PaymentStatus.pending ? {
        pending: null
    } : value == PaymentStatus.paid ? {
        paid: null
    } : value == PaymentStatus.failed ? {
        failed: null
    } : value;
}
async function to_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<TravelPackageType>): Promise<Array<_TravelPackageType>> {
    return await Promise.all(value.map(async (x)=>await to_candid_TravelPackageType_n13(_uploadFile, _downloadFile, x)));
}
function to_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Review>): Array<_Review> {
    return value.map((x)=>to_candid_Review_n16(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<IncludedService>): Array<_IncludedService> {
    return value.map((x)=>to_candid_IncludedService_n21(_uploadFile, _downloadFile, x));
}
async function to_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n26(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
