/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ThemeType = IDL.Variant({
  'nature' : IDL.Null,
  'romantic' : IDL.Null,
  'cultural' : IDL.Null,
  'adventure' : IDL.Null,
  'luxury' : IDL.Null,
  'family' : IDL.Null,
});
export const Itinerary = IDL.Record({
  'day' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const ReviewStatus = IDL.Variant({
  'submitted' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Review = IDL.Record({
  'date' : IDL.Nat,
  'user' : IDL.Text,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
  'verificationStatus' : ReviewStatus,
});
export const IncludedServiceType = IDL.Variant({
  'meals' : IDL.Null,
  'transportation' : IDL.Null,
  'tours' : IDL.Null,
  'accommodation' : IDL.Null,
  'insurance' : IDL.Null,
  'guide' : IDL.Null,
});
export const IncludedService = IDL.Record({
  'availabilityStart' : IDL.Opt(IDL.Nat),
  'cost' : IDL.Nat,
  'name' : IDL.Text,
  'type' : IncludedServiceType,
  'description' : IDL.Text,
  'availabilityEnd' : IDL.Opt(IDL.Nat),
  'rating' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const TravelPackageType = IDL.Record({
  'id' : IDL.Nat,
  'durationDays' : IDL.Nat,
  'startValidity' : IDL.Nat,
  'reviews' : IDL.Vec(Review),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'endLocation' : IDL.Text,
  'availableSpots' : IDL.Nat,
  'category' : ThemeType,
  'rating' : IDL.Nat,
  'endValidity' : IDL.Nat,
  'price' : IDL.Nat,
  'discountPercentage' : IDL.Opt(IDL.Nat),
  'includedServices' : IDL.Vec(IncludedService),
  'startLocation' : IDL.Text,
  'itinerary' : IDL.Vec(Itinerary),
  'images' : IDL.Vec(ExternalBlob),
});
export const Destination = IDL.Record({
  'id' : IDL.Nat,
  'theme' : ThemeType,
  'itineraries' : IDL.Vec(Itinerary),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'travelPackages' : IDL.Vec(TravelPackageType),
  'isFeatured' : IDL.Bool,
  'price' : IDL.Nat,
  'location' : IDL.Text,
  'images' : IDL.Vec(ExternalBlob),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'failed' : IDL.Null,
});
export const BookingStatus = IDL.Variant({
  'canceled' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'paymentStatus' : PaymentStatus,
  'user' : IDL.Principal,
  'bookingStatus' : BookingStatus,
  'stripeSessionId' : IDL.Opt(IDL.Text),
  'packageId' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDestination' : IDL.Func([Destination], [IDL.Nat], []),
  'addTravelPackage' : IDL.Func([TravelPackageType], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelBooking' : IDL.Func([IDL.Nat], [], []),
  'createBooking' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteDestination' : IDL.Func([IDL.Nat], [], []),
  'deleteTravelPackage' : IDL.Func([IDL.Nat], [], []),
  'filterByCategory' : IDL.Func(
      [ThemeType],
      [IDL.Vec(TravelPackageType)],
      ['query'],
    ),
  'filterByLocation' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TravelPackageType)],
      ['query'],
    ),
  'filterByPriceRange' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(TravelPackageType)],
      ['query'],
    ),
  'filterReviewsByRating' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Review)],
      ['query'],
    ),
  'filterServices' : IDL.Func(
      [
        IncludedServiceType,
        IDL.Nat,
        IDL.Record({ 'max' : IDL.Nat, 'min' : IDL.Nat }),
        IDL.Record({ 'end' : IDL.Opt(IDL.Nat), 'start' : IDL.Opt(IDL.Nat) }),
      ],
      [IDL.Vec(IncludedService)],
      ['query'],
    ),
  'filterServicesByAvailability' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IncludedService)],
      ['query'],
    ),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllByPriceAscending' : IDL.Func(
      [],
      [IDL.Vec(TravelPackageType)],
      ['query'],
    ),
  'getAllDestinations' : IDL.Func([], [IDL.Vec(Destination)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(IncludedService)], ['query']),
  'getAllTravelPackages' : IDL.Func(
      [],
      [IDL.Vec(TravelPackageType)],
      ['query'],
    ),
  'getAvailableServices' : IDL.Func([], [IDL.Vec(IncludedService)], ['query']),
  'getAvailableSpotsFilter' : IDL.Func(
      [],
      [IDL.Vec(TravelPackageType)],
      ['query'],
    ),
  'getBooking' : IDL.Func([IDL.Nat], [IDL.Opt(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomQuestionnaire' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getDestination' : IDL.Func([IDL.Nat], [IDL.Opt(Destination)], ['query']),
  'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getPackageCategoryFilter' : IDL.Func(
      [ThemeType],
      [IDL.Vec(TravelPackageType)],
      ['query'],
    ),
  'getReviewsForPackage' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'getServicesByType' : IDL.Func(
      [IncludedServiceType],
      [IDL.Vec(IncludedService)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTravelPackage' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(TravelPackageType)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVerifiedReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getWithAvailableSpots' : IDL.Func(
      [],
      [IDL.Vec(TravelPackageType)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchByName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TravelPackageType)],
      ['query'],
    ),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
  'updateDestination' : IDL.Func([IDL.Nat, Destination], [], []),
  'updatePaymentStatus' : IDL.Func([IDL.Nat, PaymentStatus], [], []),
  'updateTravelPackage' : IDL.Func([IDL.Nat, TravelPackageType], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ThemeType = IDL.Variant({
    'nature' : IDL.Null,
    'romantic' : IDL.Null,
    'cultural' : IDL.Null,
    'adventure' : IDL.Null,
    'luxury' : IDL.Null,
    'family' : IDL.Null,
  });
  const Itinerary = IDL.Record({
    'day' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const ReviewStatus = IDL.Variant({
    'submitted' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Review = IDL.Record({
    'date' : IDL.Nat,
    'user' : IDL.Text,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
    'verificationStatus' : ReviewStatus,
  });
  const IncludedServiceType = IDL.Variant({
    'meals' : IDL.Null,
    'transportation' : IDL.Null,
    'tours' : IDL.Null,
    'accommodation' : IDL.Null,
    'insurance' : IDL.Null,
    'guide' : IDL.Null,
  });
  const IncludedService = IDL.Record({
    'availabilityStart' : IDL.Opt(IDL.Nat),
    'cost' : IDL.Nat,
    'name' : IDL.Text,
    'type' : IncludedServiceType,
    'description' : IDL.Text,
    'availabilityEnd' : IDL.Opt(IDL.Nat),
    'rating' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const TravelPackageType = IDL.Record({
    'id' : IDL.Nat,
    'durationDays' : IDL.Nat,
    'startValidity' : IDL.Nat,
    'reviews' : IDL.Vec(Review),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'endLocation' : IDL.Text,
    'availableSpots' : IDL.Nat,
    'category' : ThemeType,
    'rating' : IDL.Nat,
    'endValidity' : IDL.Nat,
    'price' : IDL.Nat,
    'discountPercentage' : IDL.Opt(IDL.Nat),
    'includedServices' : IDL.Vec(IncludedService),
    'startLocation' : IDL.Text,
    'itinerary' : IDL.Vec(Itinerary),
    'images' : IDL.Vec(ExternalBlob),
  });
  const Destination = IDL.Record({
    'id' : IDL.Nat,
    'theme' : ThemeType,
    'itineraries' : IDL.Vec(Itinerary),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'travelPackages' : IDL.Vec(TravelPackageType),
    'isFeatured' : IDL.Bool,
    'price' : IDL.Nat,
    'location' : IDL.Text,
    'images' : IDL.Vec(ExternalBlob),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'failed' : IDL.Null,
  });
  const BookingStatus = IDL.Variant({
    'canceled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'paymentStatus' : PaymentStatus,
    'user' : IDL.Principal,
    'bookingStatus' : BookingStatus,
    'stripeSessionId' : IDL.Opt(IDL.Text),
    'packageId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDestination' : IDL.Func([Destination], [IDL.Nat], []),
    'addTravelPackage' : IDL.Func([TravelPackageType], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelBooking' : IDL.Func([IDL.Nat], [], []),
    'createBooking' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteDestination' : IDL.Func([IDL.Nat], [], []),
    'deleteTravelPackage' : IDL.Func([IDL.Nat], [], []),
    'filterByCategory' : IDL.Func(
        [ThemeType],
        [IDL.Vec(TravelPackageType)],
        ['query'],
      ),
    'filterByLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TravelPackageType)],
        ['query'],
      ),
    'filterByPriceRange' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(TravelPackageType)],
        ['query'],
      ),
    'filterReviewsByRating' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Review)],
        ['query'],
      ),
    'filterServices' : IDL.Func(
        [
          IncludedServiceType,
          IDL.Nat,
          IDL.Record({ 'max' : IDL.Nat, 'min' : IDL.Nat }),
          IDL.Record({ 'end' : IDL.Opt(IDL.Nat), 'start' : IDL.Opt(IDL.Nat) }),
        ],
        [IDL.Vec(IncludedService)],
        ['query'],
      ),
    'filterServicesByAvailability' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IncludedService)],
        ['query'],
      ),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllByPriceAscending' : IDL.Func(
        [],
        [IDL.Vec(TravelPackageType)],
        ['query'],
      ),
    'getAllDestinations' : IDL.Func([], [IDL.Vec(Destination)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(IncludedService)], ['query']),
    'getAllTravelPackages' : IDL.Func(
        [],
        [IDL.Vec(TravelPackageType)],
        ['query'],
      ),
    'getAvailableServices' : IDL.Func(
        [],
        [IDL.Vec(IncludedService)],
        ['query'],
      ),
    'getAvailableSpotsFilter' : IDL.Func(
        [],
        [IDL.Vec(TravelPackageType)],
        ['query'],
      ),
    'getBooking' : IDL.Func([IDL.Nat], [IDL.Opt(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomQuestionnaire' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getDestination' : IDL.Func([IDL.Nat], [IDL.Opt(Destination)], ['query']),
    'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getPackageCategoryFilter' : IDL.Func(
        [ThemeType],
        [IDL.Vec(TravelPackageType)],
        ['query'],
      ),
    'getReviewsForPackage' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'getServicesByType' : IDL.Func(
        [IncludedServiceType],
        [IDL.Vec(IncludedService)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTravelPackage' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(TravelPackageType)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVerifiedReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getWithAvailableSpots' : IDL.Func(
        [],
        [IDL.Vec(TravelPackageType)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TravelPackageType)],
        ['query'],
      ),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
    'updateDestination' : IDL.Func([IDL.Nat, Destination], [], []),
    'updatePaymentStatus' : IDL.Func([IDL.Nat, PaymentStatus], [], []),
    'updateTravelPackage' : IDL.Func([IDL.Nat, TravelPackageType], [], []),
  });
};

export const init = ({ IDL }) => { return []; };