/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'paymentStatus' : PaymentStatus,
  'user' : Principal,
  'bookingStatus' : BookingStatus,
  'stripeSessionId' : [] | [string],
  'packageId' : bigint,
}
export type BookingStatus = { 'canceled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export interface Destination {
  'id' : bigint,
  'theme' : ThemeType,
  'itineraries' : Array<Itinerary>,
  'name' : string,
  'description' : string,
  'travelPackages' : Array<TravelPackageType>,
  'isFeatured' : boolean,
  'price' : bigint,
  'location' : string,
  'images' : Array<ExternalBlob>,
}
export type ExternalBlob = Uint8Array;
export interface IncludedService {
  'availabilityStart' : [] | [bigint],
  'cost' : bigint,
  'name' : string,
  'type' : IncludedServiceType,
  'description' : string,
  'availabilityEnd' : [] | [bigint],
  'rating' : bigint,
}
export type IncludedServiceType = { 'meals' : null } |
  { 'transportation' : null } |
  { 'tours' : null } |
  { 'accommodation' : null } |
  { 'insurance' : null } |
  { 'guide' : null };
export interface Itinerary {
  'day' : bigint,
  'title' : string,
  'description' : string,
}
export type PaymentStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'failed' : null };
export interface Review {
  'date' : bigint,
  'user' : string,
  'comment' : string,
  'rating' : bigint,
  'verificationStatus' : ReviewStatus,
}
export type ReviewStatus = { 'submitted' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type ThemeType = { 'nature' : null } |
  { 'romantic' : null } |
  { 'cultural' : null } |
  { 'adventure' : null } |
  { 'luxury' : null } |
  { 'family' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface TravelPackageType {
  'id' : bigint,
  'durationDays' : bigint,
  'startValidity' : bigint,
  'reviews' : Array<Review>,
  'name' : string,
  'description' : string,
  'endLocation' : string,
  'availableSpots' : bigint,
  'category' : ThemeType,
  'rating' : bigint,
  'endValidity' : bigint,
  'price' : bigint,
  'discountPercentage' : [] | [bigint],
  'includedServices' : Array<IncludedService>,
  'startLocation' : string,
  'itinerary' : Array<Itinerary>,
  'images' : Array<ExternalBlob>,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDestination' : ActorMethod<[Destination], bigint>,
  'addTravelPackage' : ActorMethod<[TravelPackageType], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelBooking' : ActorMethod<[bigint], undefined>,
  'createBooking' : ActorMethod<[bigint], bigint>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteDestination' : ActorMethod<[bigint], undefined>,
  'deleteTravelPackage' : ActorMethod<[bigint], undefined>,
  'filterByCategory' : ActorMethod<[ThemeType], Array<TravelPackageType>>,
  'filterByLocation' : ActorMethod<[string], Array<TravelPackageType>>,
  'filterByPriceRange' : ActorMethod<
    [bigint, bigint],
    Array<TravelPackageType>
  >,
  'filterReviewsByRating' : ActorMethod<[bigint, bigint], Array<Review>>,
  'filterServices' : ActorMethod<
    [
      IncludedServiceType,
      bigint,
      { 'max' : bigint, 'min' : bigint },
      { 'end' : [] | [bigint], 'start' : [] | [bigint] },
    ],
    Array<IncludedService>
  >,
  'filterServicesByAvailability' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<IncludedService>
  >,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllByPriceAscending' : ActorMethod<[], Array<TravelPackageType>>,
  'getAllDestinations' : ActorMethod<[], Array<Destination>>,
  'getAllServices' : ActorMethod<[], Array<IncludedService>>,
  'getAllTravelPackages' : ActorMethod<[], Array<TravelPackageType>>,
  'getAvailableServices' : ActorMethod<[], Array<IncludedService>>,
  'getAvailableSpotsFilter' : ActorMethod<[], Array<TravelPackageType>>,
  'getBooking' : ActorMethod<[bigint], [] | [Booking]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomQuestionnaire' : ActorMethod<[string], string>,
  'getDestination' : ActorMethod<[bigint], [] | [Destination]>,
  'getMyBookings' : ActorMethod<[], Array<Booking>>,
  'getPackageCategoryFilter' : ActorMethod<
    [ThemeType],
    Array<TravelPackageType>
  >,
  'getReviewsForPackage' : ActorMethod<[bigint], Array<Review>>,
  'getServicesByType' : ActorMethod<
    [IncludedServiceType],
    Array<IncludedService>
  >,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTravelPackage' : ActorMethod<[bigint], [] | [TravelPackageType]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVerifiedReviews' : ActorMethod<[], Array<Review>>,
  'getWithAvailableSpots' : ActorMethod<[], Array<TravelPackageType>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchByName' : ActorMethod<[string], Array<TravelPackageType>>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBookingStatus' : ActorMethod<[bigint, BookingStatus], undefined>,
  'updateDestination' : ActorMethod<[bigint, Destination], undefined>,
  'updatePaymentStatus' : ActorMethod<[bigint, PaymentStatus], undefined>,
  'updateTravelPackage' : ActorMethod<[bigint, TravelPackageType], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];